version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    target-branch: "development"      
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
      - "backend"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "development"      
    commit-message:
      prefix: "chore(actions)"
    labels:
      - "ci"
      - "dependencies"

  # - package-ecosystem: "npm"
  #   directory: "/frontend"
  #   schedule:
  #     interval: "weekly"
  #   target-branch: "development"     
  #   open-pull-requests-limit: 5
  #   commit-message:
  #     prefix: "chore(deps)"
  #   labels:
  #     - "dependencies"
  #     - "frontend"
