name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            # === 1. Update System and Install Dependencies ===
            sudo dnf update -y
            sudo dnf install -y git nginx
            curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash -
            sudo dnf install -y nodejs
            sudo npm install -g pm2

            # === 2. Start/Enable NGINX ===
            sudo systemctl enable nginx
            sudo systemctl start nginx

            # === 3. Clone or Update Git Repo ===
            cd ~
            if [ ! -d "INFS803_personal-finance-tracker" ]; then
              git clone https://github.com/itsLucas-h/INFS803_personal-finance-tracker.git
            fi
            cd INFS803_personal-finance-tracker
            git fetch origin main
            git reset --hard origin/main

            # === 4. Create backend/.env ===
            cat > backend/.env <<EOF
            PORT=5000
            DB_HOST=${{ secrets.DB_HOST }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION=${{ secrets.AWS_REGION }}
            S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
            FRONTEND_URL=${{ secrets.FRONTEND_URL }}
            BACKEND_URL=${{ secrets.BACKEND_URL }}
            EOF

            # === 5. Backend: Install, Build, Run ===
            cd backend
            npm ci
            npm run build
            pm2 delete backend || true
            pm2 start dist/server.js --name backend
            cd ..

            # === 6. Create frontend/.env ===
            echo "NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }}" > frontend/.env

            # === 7. Frontend: Install, Build, Run ===
            cd frontend
            npm ci
            npm run build
            pm2 delete frontend || true
            pm2 start npm --name frontend -- start
            cd ..

            # === 8. Configure PM2 to Restart on Reboot ===
            pm2 startup
            pm2 save

            # === 9. NGINX Reverse Proxy ===
            sudo bash -c 'cat > /etc/nginx/conf.d/finance-app.conf' <<EOF
            server {
                listen 80;
                server_name ${{ secrets.ELASTIC_IP }};

                location /api/ {
                    proxy_pass http://localhost:5000/;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade \$http_upgrade;
                    proxy_set_header Connection 'upgrade';
                    proxy_set_header Host \$host;
                    proxy_cache_bypass \$http_upgrade;
                }

                location / {
                    proxy_pass http://localhost:3000/;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade \$http_upgrade;
                    proxy_set_header Connection 'upgrade';
                    proxy_set_header Host \$host;
                    proxy_cache_bypass \$http_upgrade;
                }
            }
            EOF

            sudo nginx -t && sudo systemctl restart nginx
