name: Release

on:
  push:
    branches:
      - release/*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Extract version from branch name
        id: get_version
        run: |
          VERSION=$(echo "${GITHUB_REF##*/}" | sed 's/^v//')
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Git tag
        run: |
          git tag -a "v$RELEASE_VERSION" -m "Release v$RELEASE_VERSION"
          git push origin "v$RELEASE_VERSION"

      - name: Generate GitHub Release with changelog
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: v${{ steps.get_version.outputs.version }}
          generate_release_notes: true
